version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: student_sections_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-student_user} -d ${POSTGRES_DB:-student_sections_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  # FastAPI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student_sections_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy

    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 3 &&
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    networks:
      - app_network

  # pgAdmin (опционально для управления БД через UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: student_sections_pgadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    networks:
      - app_network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
