[project]
name = "student-sections-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "passlib[bcrypt]>=1.7.4",
    "pydantic>=2.12.2",
    "python-jose>=3.5.0",
    "sqlalchemy>=2.0.44",
]
